# -*- coding: utf-8 -*-
"""
v4-int8 → C 头文件
为 ESP32-S3 部署生成 int8 量化权重
"""
import numpy as np
import tensorflow as tf
from pathlib import Path

OUT_DIR = Path(r"D:\Codex\BOSS\AIXORIGIN\snoring-ml-training\output")
ESP32_DIR = OUT_DIR / "esp32"
ESP32_DIR.mkdir(parents=True, exist_ok=True)

TFLITE_PATH = OUT_DIR / "snore_model_v4_int8.tflite"

print(f"加载 {TFLITE_PATH} ...")
interpreter = tf.lite.Interpreter(model_path=str(TFLITE_PATH))
interpreter.allocate_tensors()

# 提取量化参数
input_details = interpreter.get_input_details()[0]
output_details = interpreter.get_output_details()[0]
in_scale, in_zero = input_details['quantization']
out_scale, out_zero = output_details['quantization']
in_shape = input_details['shape']  # (1, 61, 30)
out_shape = output_details['shape']  # (1, 1)
print(f"  输入 shape: {in_shape}, scale={in_scale:.6f}, zero={in_zero}")
print(f"  输出 shape: {out_shape}, scale={out_scale:.6f}, zero={out_zero}")

# 解析 TFLite 内部权重
# 通过 tensor_details 获取所有张量
tensor_details = interpreter.get_tensor_details()
print(f"  总张量数: {len(tensor_details)}")

# 提取所有 int8 权重（CONV_2D + FULLY_CONNECTED 的 filter/bias）
weights_dict = {}
for t in tensor_details:
    name = t['name']
    # 跳过输入/输出张量（无法 read）
    if t['index'] in [input_details['index'], output_details['index']]:
        continue
    # 跳过 constant 张量（含 shape/index 数据，不是权重）
    if 'shape' in name.lower() or 'index' in name.lower() or 'iteration' in name.lower():
        continue
    try:
        tensor = interpreter.get_tensor(t['index'])
        if tensor.size > 100 and tensor.dtype in [np.int8, np.uint8]:
            # 只关心大权重（filter/bias 一般 >100 bytes）
            weights_dict[name] = tensor
    except Exception as e:
        # 跳过 null tensor（meta tensors）
        pass

print(f"  提取权重张量: {len(weights_dict)}")
for name, t in weights_dict.items():
    print(f"    {name}: shape={t.shape}, dtype={t.dtype}, size={t.size} ({t.size/1024:.1f} KB)")

# 生成 C 头文件
header_lines = [
    "// Auto-generated by export_v4_int8.py",
    "// v4 模型 int8 量化权重 - 适用于 ESP32-S3",
    f"// 模型: snore_model_v4_int8.tflite (117 KB)",
    f"// 原始: best_model_v4.h5 (1333 KB, 浮点 97.3%)",
    f"// 量化后准确率: 98.55% (val)",
    "",
    "#ifndef SNORE_MODEL_WEIGHTS_V4_INT8_H",
    "#define SNORE_MODEL_WEIGHTS_V4_INT8_H",
    "",
    "#include <stdint.h>",
    "",
    "// ===== 量化参数 =====",
    f"#define INPUT_SCALE   {in_scale:.8f}f",
    f"#define INPUT_ZERO    {int(in_zero)}",
    f"#define OUTPUT_SCALE  {out_scale:.8f}f",
    f"#define OUTPUT_ZERO   {int(out_zero)}",
    "",
    f"#define INPUT_FRAMES  {in_shape[1]}",  # 61
    f"#define INPUT_MELS    {in_shape[2]}",  # 30
    "",
]

# 添加权重数组
total_bytes = 0
for name, t in weights_dict.items():
    safe_name = name.replace('/', '_').replace(';', '_').replace(':', '_')
    flat = t.flatten()
    n = len(flat)
    total_bytes += n

    header_lines.append(f"// {name}: shape={list(t.shape)}, dtype={t.dtype}")
    header_lines.append(f"static const int8_t {safe_name}_data[{n}] = {{")

    # 格式化：每行 12 个
    for i in range(0, n, 12):
        chunk = flat[i:i+12]
        line = "    " + ", ".join(str(int(v)) for v in chunk) + ","
        header_lines.append(line)
    header_lines.append("};")
    header_lines.append(f"#define {safe_name.upper()}_LEN {n}")
    header_lines.append("")

header_lines.extend([
    f"// 总权重: {total_bytes} 字节 ({total_bytes/1024:.1f} KB)",
    "",
    "#endif // SNORE_MODEL_WEIGHTS_V4_INT8_H",
])

header_path = ESP32_DIR / "snore_model_weights_v4_int8.h"
header_path.write_text("\n".join(header_lines), encoding='utf-8')
print(f"\n💾 C 头文件: {header_path}")
print(f"   大小: {header_path.stat().st_size // 1024} KB")
print(f"   权重数据: {total_bytes} 字节 ({total_bytes/1024:.1f} KB)")

# 同时复制 .tflite 文件到 esp32 目录
import shutil
esp32_tflite = ESP32_DIR / "snore_model_v4_int8.tflite"
shutil.copy(str(TFLITE_PATH), str(esp32_tflite))
print(f"💾 TFLite 文件: {esp32_tflite} ({esp32_tflite.stat().st_size//1024} KB)")

# 量化参数单独头
quant_params = f"""// 自动生成 - int8 量化参数
#ifndef QUANT_PARAMS_V4_INT8_H
#define QUANT_PARAMS_V4_INT8_H

#define INPUT_SCALE   {in_scale:.8f}f
#define INPUT_ZERO    {int(in_zero)}
#define OUTPUT_SCALE  {out_scale:.8f}f
#define OUTPUT_ZERO   {int(out_zero)}

#define INPUT_FRAMES  61
#define INPUT_MELS    30
#define THRESHOLD     0.65f

#endif
"""
quant_path = ESP32_DIR / "quant_params_v4_int8.h"
quant_path.write_text(quant_params, encoding='utf-8')
print(f"💾 量化参数: {quant_path}")
