"""Export with release gates: int8 TFLite, C headers, golden files and the model card (spec section 11)."""
from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import math
import os
import shutil
from datetime import date, datetime
from pathlib import Path

import numpy as np
from scipy.signal import butter, sosfilt

from v5 import features as F
from v5 import golden as G
from v5.config import ROOT, load_config, resolve
from v5.doa import DoaParams, DoaTracker, gcc_phat
from v5.streaming import ACTIVE, CONFIRMED, IDLE, FsmParams, run_sequence

GEN_DIR = ROOT / "esp32_firmware" / "v5" / "generated"
STATE_CODE = {IDLE: 0, ACTIVE: 1, CONFIRMED: 2}
EVENT_CODE = {None: 0, "episode_start": 1, "episode_end": 2}
SIDE_CODE = {"unknown": 0, "left": 1, "right": 2}
HEADER_NOTE = "// Auto-generated by v5/export.py from the frozen feature spec; do not edit by hand.\n"
ALLOWED_TFLITE_OPS = {"CONV_2D", "MAX_POOL_2D", "MEAN", "FULLY_CONNECTED", "LOGISTIC", "RESHAPE", "QUANTIZE", "DEQUANTIZE"}
PARITY_LIMITS = {"delta_auc": 0.005, "agreement": 0.99, "max_abs_diff": 0.05}
HEADER_FILES = ("feature_spec.h", "mel_filterbank.h", "model_meta.h", "model_data.h", "model_data.c")
PROMOTED_FILES = ["snore_v5_int8.tflite", "robustness.json", "export_info.json", "export_status.json", "test_metrics.json", "feature_spec.json", *HEADER_FILES]
# C capacities from esp32_firmware/v5/snore_episode_fsm.h; FSM parameters must fit them (one burst or hit per tick worst case)
FSM_MAX_HIST, FSM_MAX_BURSTS, FSM_MAX_HITS = 64, 64, 64


class ExportError(RuntimeError):
    """A release gate failed; nothing was promoted."""


def check_threshold_binding(model_path, thr: dict) -> str:
    from v5.train import file_sha256

    expected = thr.get("model_sha256")
    actual = file_sha256(model_path)
    if not expected or expected != actual:
        raise ExportError(f"threshold.json is bound to model sha256 {expected}, but {model_path} has {actual}; re-run `python -m v5.train final`")
    return actual


def _write_json_atomic(path: Path, payload: dict) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=1), encoding="utf-8")
    os.replace(tmp, path)


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def bundle_hashes(bundle_dir: Path) -> dict:
    """SHA-256 of every file of an evaluation bundle, keyed by its path inside the bundle."""
    return {str(p.relative_to(bundle_dir)): _sha256_bytes(p.read_bytes()) for p in sorted(bundle_dir.rglob("*")) if p.is_file()}


RESET_LEDGER = "test_consumption_resets.log"  # persistent, next to the record; every reset reason lands here before anything is deleted


def _ledger_entries(out_dir: Path) -> list[tuple[datetime, str]]:
    path = Path(out_dir) / RESET_LEDGER
    if not path.exists():
        return []
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        stamp = line.split(" ", 1)[0]
        try:
            out.append((datetime.fromisoformat(stamp).replace(tzinfo=None), line))
        except ValueError:
            continue
    return out


def reset_test_record(out_dir, reason: str) -> Path:
    """The only sanctioned way to evaluate the test split again: the reason is appended to the ledger
    (printed in the model card) before the record and every evaluation bundle are removed."""
    out_dir = Path(out_dir)
    if not reason or len(reason.strip()) < 10:
        raise ExportError("a reset needs a reason of at least 10 characters; it is printed in the model card")
    ledger = out_dir / RESET_LEDGER
    with open(ledger, "a", encoding="utf-8") as fh:
        fh.write(f"{datetime.now().isoformat(timespec='seconds')} reset: {reason.strip()}\n")
    record, bundles = out_dir / "test_consumption.json", out_dir / "test_evaluation"
    if record.exists():
        record.unlink()
    if bundles.exists():
        shutil.rmtree(bundles)
    return ledger


def _require_documented_reset(out_dir: Path, reset_hint: str) -> None:
    """A fresh claim is refused while evidence of an earlier evaluation exists without a later ledger entry."""
    bundles = out_dir / "test_evaluation"
    if bundles.exists() and any(bundles.iterdir()):
        raise ExportError(f"evaluation bundles exist in {bundles} without a record; a fresh evaluation needs a documented reset. " + reset_hint)
    info = out_dir / "deliverables" / "export_info.json"
    if info.exists():
        try:
            exported_at = datetime.fromisoformat(json.loads(info.read_text(encoding="utf-8")).get("exported_at", "")).replace(tzinfo=None)
        except (ValueError, TypeError):
            exported_at = datetime.min
        if not any(stamp >= exported_at and " reset: " in line for stamp, line in _ledger_entries(out_dir)):
            raise ExportError(f"a release exported at {exported_at.isoformat(timespec='seconds')} exists but the ledger {out_dir / RESET_LEDGER} has no reset entry after it; "
                              "the earlier test evaluation must be reset with a documented reason first. " + reset_hint)


def claim_test_split(out_dir, manifest_sha: str, model_sha: str, tau: float):
    """Enforce the one-time test evaluation.

    Returns None when this model may evaluate the test split now (a fresh record is written), or the
    completed evaluation bundle when the same model re-exports at the same threshold. Raises for another
    model or manifest, another tau (the bundle's metrics and parity agreement are tau-specific), a bundle
    whose files differ from the hashes in the record, and an incomplete record left by an interrupted attempt."""
    out_dir = Path(out_dir)
    record = out_dir / "test_consumption.json"
    reset_hint = ("If that is a deliberate decision, run `python -m v5.export reset-test-record --reason '...'`: it writes the reason "
                  f"to {out_dir / RESET_LEDGER} (printed in the model card) and only then removes {record.name} and the evaluation bundles.")
    if not record.exists():
        _require_documented_reset(out_dir, reset_hint)
    if record.exists():
        prev = json.loads(record.read_text(encoding="utf-8"))
        if prev["manifest_sha256"] != manifest_sha:
            raise ExportError(f"the test split was consumed on manifest {prev['manifest_sha256'][:12]} by model {prev['model_sha256'][:12]} on {prev['at']}; "
                              "a rebuilt manifest does not grant a fresh evaluation. " + reset_hint)
        if prev["model_sha256"] != model_sha:
            raise ExportError(f"the test split of this manifest was already consumed by model {prev['model_sha256'][:12]} on {prev['at']}; "
                              "evaluating another model would turn the test set into a development set. " + reset_hint)
        bundle_dir = out_dir / "test_evaluation" / model_sha
        if not prev.get("complete") or not (bundle_dir / "results.json").exists():
            raise ExportError(f"a previous evaluation of model {model_sha[:12]} was interrupted before its bundle was completed; "
                              "the record is locked. " + reset_hint)
        if prev.get("tau") != tau:
            raise ExportError(f"the test split was evaluated at tau {prev.get('tau')} but the deployed threshold is now {tau}; the bundle's metrics and parity "
                              "agreement hold only at the evaluated tau, and a re-calibrated model may not read the test split again. " + reset_hint)
        expected = prev.get("bundle")
        actual = bundle_hashes(bundle_dir)
        if not expected or actual != expected:
            changed = sorted(set(expected or {}) ^ set(actual) | {k for k in (expected or {}) if actual.get(k) != expected[k]})
            raise ExportError(f"evaluation bundle {bundle_dir} does not match the hashes in {record} ({changed or 'no hashes recorded'}); "
                              "its results cannot be trusted. " + reset_hint)
        results = json.loads((bundle_dir / "results.json").read_text(encoding="utf-8"))
        if results.get("tflite_sha256") != expected.get("snore_v5_int8.tflite") or results.get("tau") != tau:
            raise ExportError(f"evaluation bundle {bundle_dir} is internally inconsistent; its results cannot be trusted. " + reset_hint)
        results["bundle_dir"] = str(bundle_dir)
        return results
    _write_json_atomic(record, {"manifest_sha256": manifest_sha, "model_sha256": model_sha, "tau": tau, "at": datetime.now().isoformat(timespec="seconds"), "complete": False})
    return None


def persist_test_results(out_dir, results: dict, tflite: bytes, golden_files: dict) -> Path:
    """Write the immutable evaluation bundle (staged, then renamed), then complete the record with the hash of every bundle file."""
    out_dir = Path(out_dir)
    record = out_dir / "test_consumption.json"
    prev = json.loads(record.read_text(encoding="utf-8"))
    final = out_dir / "test_evaluation" / prev["model_sha256"]
    if final.exists() or prev.get("complete"):
        raise ExportError(f"evaluation bundle {final} already exists; a completed evaluation is immutable")
    results = {**results, "tflite_sha256": _sha256_bytes(tflite), "tau": prev["tau"]}  # computed here, never trusted from the caller
    tmp = final.with_name(final.name + ".tmp")
    if tmp.exists():
        shutil.rmtree(tmp)
    (tmp / "golden").mkdir(parents=True)
    (tmp / "snore_v5_int8.tflite").write_bytes(tflite)
    for name, data in golden_files.items():
        (tmp / "golden" / name).write_bytes(data)
    (tmp / "results.json").write_text(json.dumps(results, indent=1), encoding="utf-8")
    os.rename(tmp, final)
    prev["bundle"] = bundle_hashes(final)
    prev["complete"] = True
    _write_json_atomic(record, prev)
    return final


def check_manifest_binding(thr: dict, metrics: dict, manifest_sha: str) -> None:
    """The deployed model and its threshold must have been selected and calibrated on the manifest being exported."""
    for name, d in (("threshold.json", thr), ("deployed metrics.json", metrics)):
        if d.get("manifest_sha256") != manifest_sha:
            raise ExportError(f"{name} is bound to manifest {str(d.get('manifest_sha256'))[:12]} but the current manifest is {manifest_sha[:12]}; "
                              "re-run `python -m v5.train final` on this manifest")


def precheck_release(model_path, thr: dict) -> str:
    from v5.versioning import check_model_version

    try:
        check_model_version(str(thr.get("model_version", "")))
    except ValueError as exc:
        raise ExportError(str(exc)) from exc
    return check_threshold_binding(model_path, thr)


def to_tflite_int8(model, rep_X) -> bytes:
    """Full-integer conversion of the probability model (sigmoid on top of the logit model).

    Keras-model conversion goes through a SavedModel export, which freezes the BatchNormalization
    variables; converting a concrete function of the Keras 3 model leaves READ_VARIABLE ops behind."""
    import keras
    import tensorflow as tf

    wrapped = keras.Model(model.input, keras.layers.Activation("sigmoid", name="prob")(model.output))
    converter = tf.lite.TFLiteConverter.from_keras_model(wrapped)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    rep = np.asarray(rep_X, dtype=np.float32)

    def representative():
        for i in range(len(rep)):
            yield [rep[i: i + 1]]

    converter.representative_dataset = representative
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    return converter.convert()


def quant_params(tflite: bytes) -> dict:
    from v5.evaluate import make_interpreter

    it = make_interpreter(tflite)
    it.allocate_tensors()
    i, o = it.get_input_details()[0], it.get_output_details()[0]
    return {"input_scale": float(i["quantization"][0]), "input_zero_point": int(i["quantization"][1]), "output_scale": float(o["quantization"][0]),
            "output_zero_point": int(o["quantization"][1]), "input_shape": [int(v) for v in i["shape"]], "output_shape": [int(v) for v in o["shape"]],
            "input_dtype": np.dtype(i["dtype"]).name, "output_dtype": np.dtype(o["dtype"]).name}


def tflite_ops(tflite: bytes):
    """Operator names of the model, or None when the interpreter cannot enumerate them (a gate failure)."""
    from v5.evaluate import make_interpreter

    try:
        it = make_interpreter(tflite)
        it.allocate_tensors()
        ops = sorted({d["op_name"] for d in it._get_ops_details() if d["op_name"] != "DELEGATE"})
        return ops or None
    except Exception:
        return None


def validate_tflite(tflite: bytes) -> dict:
    try:
        qp = quant_params(tflite)
    except Exception as exc:
        raise ExportError(f"tflite model cannot be loaded: {type(exc).__name__}: {exc}") from exc
    problems = []
    if qp["input_dtype"] != "int8" or qp["output_dtype"] != "int8":
        problems.append(f"dtypes {qp['input_dtype']}/{qp['output_dtype']} are not int8")
    if qp["input_shape"] != [1, F.N_FRAMES, F.N_MELS, 1] or qp["output_shape"] != [1, 1]:
        problems.append(f"shapes {qp['input_shape']} -> {qp['output_shape']}")
    ops = tflite_ops(tflite)
    if ops is None:  # fail closed: an unverifiable operator set never ships
        problems.append("operator set could not be enumerated by the interpreter")
    else:
        extra = sorted(set(ops) - ALLOWED_TFLITE_OPS)
        if extra:
            problems.append(f"operators outside the TFLM-safe set: {extra}")
    if problems:
        raise ExportError("; ".join(problems))
    return {**qp, "ops": ops, "ops_checked": True}


def check_parity(parity: dict) -> None:
    """Decided from the numbers and the current limits; a stored `passed` flag is never trusted."""
    try:
        ok = (float(parity["delta_auc"]) < PARITY_LIMITS["delta_auc"] and float(parity["agreement"]) >= PARITY_LIMITS["agreement"]
              and float(parity["max_abs_diff"]) <= PARITY_LIMITS["max_abs_diff"])
    except (KeyError, TypeError, ValueError) as exc:
        raise ExportError(f"int8 parity result is incomplete: {parity}") from exc
    if not ok:
        raise ExportError(f"int8 parity gate failed: {parity} (limits {PARITY_LIMITS})")


def arena_estimate(model, tflite_bytes: int) -> dict:
    sizes = [int(np.prod(model.input_shape[1:]))]
    for layer in model.layers:
        shape = getattr(layer, "output", None)
        if shape is not None and hasattr(shape, "shape") and len(shape.shape) > 1:
            sizes.append(int(np.prod([int(d) for d in shape.shape[1:]])))
    pairs = [a + b for a, b in zip(sizes, sizes[1:])] or sizes
    return {"activation_bytes_estimate": int(max(pairs)) + 2048, "largest_tensor_bytes": int(max(sizes)), "flash_bytes": int(tflite_bytes),
            "note": "int8 activations; two largest consecutive tensors plus scratch; measure the real arena on the device"}


def write_c_array(data: bytes, name: str, h_path, c_path) -> None:
    Path(h_path).write_text(HEADER_NOTE + "#pragma once\n#include <stddef.h>\n\n" + f"extern const unsigned char {name}[];\nextern const unsigned int {name}_len;\n", encoding="utf-8")
    rows = [", ".join(f"0x{b:02x}" for b in data[i: i + 12]) for i in range(0, len(data), 12)]
    body = ",\n".join("    " + r for r in rows)
    Path(c_path).write_text(HEADER_NOTE + f'#include "{Path(h_path).name}"\n\n' + f"const unsigned char {name}[] __attribute__((aligned(16))) = {{\n{body}\n}};\n" + f"const unsigned int {name}_len = {len(data)};\n", encoding="utf-8")


def write_feature_spec_h(path) -> None:
    lines = [HEADER_NOTE + "#pragma once", "", f"#define SF_FEATURE_SPEC_VERSION {F.FEATURE_SPEC_VERSION}", f"#define SF_SAMPLE_RATE {F.SR}", f"#define SF_WIN {F.WIN}",
             f"#define SF_STREAM_HOP {F.STREAM_HOP}", f"#define SF_N_FFT {F.N_FFT}", f"#define SF_HOP {F.HOP}", f"#define SF_N_FRAMES {F.N_FRAMES}", f"#define SF_N_BINS {F.N_BINS}",
             f"#define SF_N_MELS {F.N_MELS}", f"#define SF_FMIN {F.FMIN:.1f}f", f"#define SF_FMAX {F.FMAX:.1f}f", f"#define SF_LOG_EPS {F.LOG_EPS:g}f", f"#define SF_NORM_DIV {F.NORM_DIV:.1f}f",
             f"#define SF_FEATURE_DIM {F.FEATURE_DIM}", "#define SF_PI 3.14159265358979323846f", ""]
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def write_mel_filterbank_h(path) -> None:
    starts, lens, offs, weights = [], [], [], []
    for start, w in F.sparse_filterbank():
        starts.append(start)
        lens.append(len(w))
        offs.append(len(weights))
        weights.extend(float(v) for v in w)
    fmt = lambda xs: ", ".join(str(int(x)) for x in xs)
    body = ",\n".join("    " + ", ".join(f"{v:.8e}f" for v in weights[i: i + 6]) for i in range(0, len(weights), 6))
    text = (HEADER_NOTE + "#pragma once\n#include <stdint.h>\n\n" + f"#define SF_MEL_W_LEN {len(weights)}\n"
            + f"static const uint16_t sf_mel_start[{F.N_MELS}] = {{{fmt(starts)}}};\n" + f"static const uint16_t sf_mel_len[{F.N_MELS}] = {{{fmt(lens)}}};\n"
            + f"static const uint16_t sf_mel_off[{F.N_MELS}] = {{{fmt(offs)}}};\n" + f"static const float sf_mel_w[{len(weights)}] = {{\n{body}\n}};\n")
    Path(path).write_text(text, encoding="utf-8")


def check_fsm_capacity(fsm: FsmParams) -> None:
    window = fsm.confirm_ticks + fsm.hold_ticks + 1
    if fsm.hold_ticks + 1 > FSM_MAX_HIST or window > FSM_MAX_BURSTS or window > FSM_MAX_HITS:
        raise ExportError(f"FSM parameters exceed the C capacities (hold {fsm.hold_ticks} + 1 <= {FSM_MAX_HIST}, confirm + hold + 1 = {window} <= {min(FSM_MAX_BURSTS, FSM_MAX_HITS)})")


def write_feature_spec_json(path) -> None:
    Path(path).write_text(json.dumps(F.feature_spec_dict(), indent=1), encoding="utf-8")


def write_model_meta_h(path, qp: dict, tau: float, fsm: FsmParams, model_version: str) -> None:
    check_fsm_capacity(fsm)
    lines = [HEADER_NOTE + "#pragma once", "", f'#define MODEL_VERSION "{model_version}"', f"#define FEATURE_SPEC_VERSION {F.FEATURE_SPEC_VERSION}",
             f"#define INPUT_SCALE {qp['input_scale']:.10f}f", f"#define INPUT_ZERO_POINT {qp['input_zero_point']}", f"#define OUTPUT_SCALE {qp['output_scale']:.10f}f",
             f"#define OUTPUT_ZERO_POINT {qp['output_zero_point']}", f"#define SNORE_THRESHOLD {np.float32(tau):.9g}f", f"#define FSM_TICK_MS {fsm.tick_ms}", f"#define FSM_HOLD_TICKS {fsm.hold_ticks}",
             f"#define FSM_CONFIRM_TICKS {fsm.confirm_ticks}", f"#define FSM_VERIFY_TICKS {fsm.verify_ticks}", f"#define FSM_MIN_BURSTS {fsm.min_bursts}",
             f"#define FSM_PERIOD_MIN_TICKS {fsm.period_min_ticks}", f"#define FSM_PERIOD_MAX_TICKS {fsm.period_max_ticks}", ""]
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def fsm_trace_sequence(seed: int = 0, tau: float = 0.65) -> list[float]:
    rng = np.random.default_rng(seed)
    seq: list[float] = []

    def periodic(cycles, burst, gap):
        for _ in range(cycles):
            seq.extend(0.85 + 0.1 * rng.random() for _ in range(burst))
            seq.extend(0.1 * rng.random() for _ in range(gap))

    seq.extend([0.05] * 10)
    periodic(8, 3, 5)
    seq.extend([0.05] * 60)
    seq.extend([0.92] * 40)
    seq.extend([0.05] * 100)
    periodic(6, 2, 6)
    seq.extend([0.3] * 20)
    seq.extend(float(v) for v in rng.random(200))
    periodic(10, 4, 4)
    seq.extend([0.02] * 80)
    out = []
    for v in seq:
        v = round(float(v), 3)
        if abs(v - tau) < 1e-9:
            v += 0.001
        out.append(v)
    return out


def fsm_boundary_params(fsm: FsmParams) -> FsmParams:
    """The largest confirm window fsm_init accepts (confirm + hold + 1 == FSM_MAX_HITS): the C hit and burst buffers must fill without losing a tick."""
    return dataclasses.replace(fsm, hold_ticks=12, confirm_ticks=FSM_MAX_HITS - 12 - 1, verify_ticks=30, min_bursts=3, period_min_ticks=3, period_max_ticks=14)


def fsm_boundary_sequence(tau: float) -> list[float]:
    """A run of hits longer than the retained window, then periodic bursts that confirm, then silence that ends the episode."""
    seq = [0.05] * 10 + [0.92] * 100 + [0.05] * 30
    for _ in range(8):
        seq += [0.9] * 3 + [0.05] * 5
    seq += [0.02] * 80
    return [v + 0.001 if abs(v - tau) < 1e-9 else v for v in seq]


def write_golden_fsm(path, params: FsmParams, seed: int = 0, seq: list[float] | None = None) -> None:
    seq = fsm_trace_sequence(seed, params.tau) if seq is None else seq
    levels = [-40.0 + 5.0 * np.sin(k / 7.0) for k in range(len(seq))]
    events, states, actives = run_sequence(seq, params, levels)
    ev_by_tick = {e["tick"]: e for e in events}
    lines = [f"{params.tau:g} {params.tick_ms} {params.hold_ticks} {params.confirm_ticks} {params.verify_ticks} {params.min_bursts} {params.period_min_ticks} {params.period_max_ticks}"]
    for k, (p, st, ac) in enumerate(zip(seq, states, actives)):
        ev = ev_by_tick.get(k)
        code = EVENT_CODE[ev["type"] if ev else None]
        if ev is not None and ev["type"] == "episode_end":
            tail = f"{ev['duration_s']:.3f} {ev['mean_p']:.6f} {ev['n_bursts']} {ev['n_hits']} {ev['level_dbfs']:.4f}"
        else:
            tail = "0 0 0 0 0"
        lines.append(f"{p:.3f} {STATE_CODE[st]} {1 if ac else 0} {code} {tail}")
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def _delayed(x, d: float) -> np.ndarray:
    n = len(x)
    f = np.fft.rfftfreq(n, 1.0 / F.SR)
    return np.fft.irfft(np.fft.rfft(x) * np.exp(-2j * np.pi * f * d / F.SR), n=n)


def _burst(rng, sos):
    return sosfilt(sos, rng.standard_normal(576))[64:] * 0.1


def _uncorrelated_pair(rng, sos, params: DoaParams):
    """An uncorrelated frame pair whose PHAT peak ratio is at least 0.05 away from min_ratio, so that
    float32 (C) and float64 (Python) cannot disagree on validity at the boundary."""
    while True:
        l, r = F.float_to_int16(_burst(rng, sos)), F.float_to_int16(_burst(rng, sos))
        _, ratio = gcc_phat(F.int16_to_float(l), F.int16_to_float(r), params.max_lag, params.fs, params.band, params.n_fft)
        if abs(ratio - params.min_ratio) >= 0.05:
            return l, r


def doa_golden_cases(seed: int = 0, params: DoaParams = DoaParams()):
    rng = np.random.default_rng(seed)
    sos = butter(4, [100, 2000], btype="band", fs=F.SR, output="sos")
    cases = []
    for d in (-3.0, -2.0, -1.5, -1.0, 0.0, 1.0, 1.5, 2.0, 3.0):
        l = _burst(rng, sos)
        cases.append((F.float_to_int16(l), F.float_to_int16(_delayed(l, d))))
    cases.append(_uncorrelated_pair(rng, sos, params))
    t = np.arange(512) / F.SR  # loud tone entirely above the 60-3000 Hz band: no usable peak, must be invalid
    tone = 0.3 * np.sin(2 * np.pi * 5000.0 * t)
    cases.append((F.float_to_int16(tone), F.float_to_int16(np.roll(tone, 2))))
    return cases


def write_golden_doa_cases(path, params: DoaParams, seed: int = 0) -> None:
    cases = doa_golden_cases(seed, params)
    with open(path, "wb") as fh:
        fh.write(np.array([len(cases), params.n_fft, params.max_lag], dtype="<i4").tobytes())
        for l, r in cases:
            lag, ratio = gcc_phat(F.int16_to_float(l), F.int16_to_float(r), params.max_lag, params.fs, params.band, params.n_fft)
            fh.write(l.astype("<i2").tobytes())
            fh.write(r.astype("<i2").tobytes())
            fh.write(np.array([lag, ratio], dtype="<f4").tobytes())


def doa_tracker_frames(seed: int = 0, params: DoaParams = DoaParams()):
    rng = np.random.default_rng(seed)
    sos = butter(4, [100, 2000], btype="band", fs=F.SR, output="sos")
    frames = []
    for _ in range(25):  # source on the left: signal reaches L two samples early
        l = _burst(rng, sos)
        frames.append((F.float_to_int16(l), F.float_to_int16(_delayed(l, 2.0))))
    for _ in range(5):  # quiet frames, below the noise floor margin
        q = 1e-5 * rng.standard_normal(512)
        frames.append((F.float_to_int16(q), F.float_to_int16(q)))
    for _ in range(10):  # uncorrelated pairs, kept away from the ratio boundary
        frames.append(_uncorrelated_pair(rng, sos, params))
    return frames


def write_golden_doa_tracker(path, params: DoaParams, seed: int = 0) -> None:
    frames = doa_tracker_frames(seed, params)
    tracker = DoaTracker(params)
    with open(path, "wb") as fh:
        fh.write(np.array([len(frames), params.n_fft], dtype="<i4").tobytes())
        fh.write(np.array([params.spacing_m], dtype="<f4").tobytes())
        for l, r in frames:
            lag, valid = tracker.frame(F.int16_to_float(l), F.int16_to_float(r))
            fh.write(l.astype("<i2").tobytes())
            fh.write(r.astype("<i2").tobytes())
            fh.write(np.array([1 if valid else 0], dtype="<i4").tobytes())
            fh.write(np.array([lag], dtype="<f4").tobytes())
        ep = tracker.episode()
        fh.write(np.array([SIDE_CODE[ep["side"]]], dtype="<i4").tobytes())
        fh.write(np.array([ep["lag_samples"], ep["lag_ms"], ep["conf"]], dtype="<f4").tobytes())
        fh.write(np.array([ep["n_valid"]], dtype="<i4").tobytes())


def write_headers_only(gen_dir, golden_dir, fsm: FsmParams, doa: DoaParams) -> None:
    gen_dir, golden_dir = Path(gen_dir), Path(golden_dir)
    gen_dir.mkdir(parents=True, exist_ok=True)
    golden_dir.mkdir(parents=True, exist_ok=True)
    write_feature_spec_h(gen_dir / "feature_spec.h")
    write_feature_spec_json(gen_dir / "feature_spec.json")
    write_mel_filterbank_h(gen_dir / "mel_filterbank.h")
    write_golden_fsm(golden_dir / "fsm_trace.txt", fsm)
    bp = fsm_boundary_params(fsm)
    write_golden_fsm(golden_dir / "fsm_trace_boundary.txt", bp, seq=fsm_boundary_sequence(bp.tau))
    write_golden_doa_cases(golden_dir / "doa_cases.bin", doa)
    write_golden_doa_tracker(golden_dir / "doa_tracker.bin", doa)


RELEASE_BOUND_REPORTS = ("model_card.md", "benchmark_nights.md", "doa_sim.md", "cross_collection.md")  # derived from a release; regenerated after every export


def _build_new_tree(live: Path, new: Path, stage: Path, files, golden: bool, drop=()) -> None:
    if new.exists():
        shutil.rmtree(new)
    if live.exists():
        shutil.copytree(live, new)
    else:
        new.mkdir(parents=True)
    for name in drop:  # a report bound to the previous release must not survive next to a new export_status "ok"
        if (new / name).exists():
            (new / name).unlink()
    for name in files:
        shutil.copy(stage / name, new / name)
    if golden:
        if (new / "golden").exists():
            shutil.rmtree(new / "golden")
        shutil.copytree(stage / "golden", new / "golden")


def promote(stage, deliv, gen_dir) -> None:
    """Transactional promotion: complete sibling trees are built first, then both live directories
    are swapped by rename; any failure rolls both back to the previous release."""
    stage, deliv, gen_dir = Path(stage), Path(deliv), Path(gen_dir)
    new_deliv, new_gen = deliv.with_name(deliv.name + ".new"), gen_dir.with_name(gen_dir.name + ".new")
    _build_new_tree(deliv, new_deliv, stage, PROMOTED_FILES, golden=True, drop=RELEASE_BOUND_REPORTS)
    _build_new_tree(gen_dir, new_gen, stage, HEADER_FILES, golden=False)
    swapped = []  # (live, bak): bak is None when there was no previous release; installed lives are removed on rollback
    try:
        for live, new in ((deliv, new_deliv), (gen_dir, new_gen)):
            bak = live.with_name(live.name + ".bak")
            if bak.exists():
                shutil.rmtree(bak)
            if live.exists():
                os.rename(live, bak)
                swapped.append((live, bak))
            else:
                swapped.append((live, None))
            os.rename(new, live)
    except Exception:
        for live, bak in reversed(swapped):
            if live.exists():  # partially or newly installed tree: never leave it behind
                shutil.rmtree(live)
            if bak is not None and bak.exists():
                os.rename(bak, live)
        for new in (new_deliv, new_gen):
            if new.exists():
                shutil.rmtree(new)
        raise
    for _, bak in swapped:  # post-commit cleanup is best-effort: the new release is already live
        if bak is not None and bak.exists():
            try:
                shutil.rmtree(bak)
            except OSError as exc:
                print(f"[export] warning: could not remove backup {bak}: {exc}")


def _write_status(target_dir: Path, status: str, **extra) -> None:
    target_dir.mkdir(parents=True, exist_ok=True)
    (target_dir / "export_status.json").write_text(json.dumps({"status": status, "at": datetime.now().isoformat(timespec="seconds"), **extra}, indent=1))


def export_model(cfg: dict, model_path=None, threshold_path=None) -> dict:
    import keras

    from v5.data import manifest as M
    from v5.data.dataset import precompute_features
    from v5.evaluate import clip_metrics, int8_parity, int8_probs, predict_probs, robustness_sweep
    from v5.model import check_ops

    out = Path(cfg["paths"]["out_dir"])
    deliv, stage = out / "deliverables", out / "export_stage"
    try:
        if stage.exists():
            shutil.rmtree(stage)
        golden = stage / "golden"
        golden.mkdir(parents=True)
        thr = json.loads(Path(threshold_path or out / "deployed" / "threshold.json").read_text())
        tau, model_version = float(thr["tau"]), thr["model_version"]
        fsm = FsmParams.from_config(tau, thr["fsm"])
        doa = DoaParams(spacing_m=float(cfg["doa"]["spacing_m"]))
        model_file = Path(model_path or out / "deployed" / "model.keras")
        model_sha = precheck_release(model_file, thr)  # version rule and model binding, before any manifest or test-split access
        model = keras.models.load_model(model_file, compile=False)
        check_ops(model)
        from v5.train import file_sha256

        rows = M.read_manifest(out / "manifest.csv")
        manifest_sha = file_sha256(out / "manifest.csv")
        metrics_file = model_file.parent / "metrics.json"
        check_manifest_binding(thr, json.loads(metrics_file.read_text()) if metrics_file.exists() else {}, manifest_sha)  # before any test-split access
        persisted = claim_test_split(out, manifest_sha, model_sha, tau)  # None: evaluate once now; dict: reuse the immutable bundle (same model, same tau)
        _, audio, _ = M.load_cache(out)
        y = np.array([r["label"] for r in rows])
        write_headers_only(stage, golden, fsm, doa)  # also emits feature_spec.json
        if persisted is None:
            tr = M.split_indices(rows, "train")
            te = M.split_indices(rows, "test", allow_test=True)  # the single sanctioned read of the test split
            rng = np.random.default_rng(cfg["seed"])
            tflite = to_tflite_int8(model, precompute_features(audio[rng.choice(tr, size=min(500, len(tr)), replace=False)]))
            valid = validate_tflite(tflite)
            snore = [audio[i] for i in te if y[i] == 1][:4]
            noise = [audio[i] for i in te if y[i] == 0][:4]
            names, gx, gX, gq = G.make_golden(snore, noise, scale=valid["input_scale"], zero_point=valid["input_zero_point"])
            G.write_golden_npz(golden / "features.npz", names, gx, gX, gq, valid["input_scale"], valid["input_zero_point"])
            G.write_golden_bin(golden / "features.bin", gx, gX, gq, valid["input_scale"], valid["input_zero_point"])
            Xt = precompute_features(audio[te])
            p_fp, p_i8 = predict_probs(model, Xt), int8_probs(tflite, Xt)
            parity = int8_parity(p_fp, p_i8, y[te], tau)
            test_metrics = {"float": clip_metrics(y[te], p_fp, tau), "int8": clip_metrics(y[te], p_i8, tau)}
            bench_noise = audio[[r["id"] for r in rows if r["split"] == "bench" and r["source"] == "mssnsd" and r["label"] == 0]]  # never snore material
            robustness = robustness_sweep(model, audio[te], y[te], bench_noise, tau, seed=cfg["seed"])
            results = {"tflite_sha256": hashlib.sha256(tflite).hexdigest(), "qp": valid, "parity": parity, "test_metrics": test_metrics, "robustness": robustness, "n_test": int(len(te))}
            persist_test_results(out, results, tflite, {"features.npz": (golden / "features.npz").read_bytes(), "features.bin": (golden / "features.bin").read_bytes()})
        else:  # repeat export of the same model: the bundle is the artifact, no test access at all
            bundle = Path(persisted["bundle_dir"])
            tflite = (bundle / "snore_v5_int8.tflite").read_bytes()  # every bundle file was hash-checked against the record in claim_test_split
            valid = validate_tflite(tflite)
            for name in ("features.npz", "features.bin"):
                shutil.copy(bundle / "golden" / name, golden / name)
            parity, test_metrics, robustness, results = persisted["parity"], persisted["test_metrics"], persisted["robustness"], persisted
        (stage / "snore_v5_int8.tflite").write_bytes(tflite)
        write_c_array(tflite, "snore_v5_int8_tflite", stage / "model_data.h", stage / "model_data.c")
        write_model_meta_h(stage / "model_meta.h", valid, tau, fsm, model_version)
        check_parity(parity)
        from v5.benchmark_nights import benchmark_config
        from v5.doa_sim import sweep_config

        info = {"fsm": fsm.to_dict(), "doa_sweep": sweep_config(cfg, rows), "benchmark": benchmark_config(cfg),  # the reports must bind to exactly these
                "model_version": model_version, "model_sha256": model_sha, "manifest_sha256": manifest_sha, "tau": tau, "run": thr.get("run"), "calib": thr.get("calib"), "tflite_bytes": len(tflite),
                "tflite_sha256": hashlib.sha256(tflite).hexdigest(), "params": int(model.count_params()), "qp": valid, "parity": parity, "parity_limits": PARITY_LIMITS,
                "arena": arena_estimate(model, len(tflite)), "test": test_metrics, "n_test": int(results["n_test"]), "test_evaluated_from_bundle": persisted is not None,
                "exported_at": datetime.now().isoformat(timespec="seconds")}
        (stage / "export_info.json").write_text(json.dumps(info, indent=1))
        (stage / "test_metrics.json").write_text(json.dumps(test_metrics, indent=1))
        (stage / "robustness.json").write_text(json.dumps(robustness, indent=1))
        _write_status(stage, "ok", model_version=model_version, model_sha256=model_sha, tflite_sha256=info["tflite_sha256"])  # travels inside the swap
        promote(stage, deliv, GEN_DIR)
        try:
            shutil.rmtree(stage)
        except OSError as exc:  # the release is live; leftover stage files are harmless
            print(f"[export] warning: could not remove {stage}: {exc}")
        return info
    except Exception as exc:  # the live release and its status stay untouched; the attempt is recorded next to the stage
        failed = {"error": f"{type(exc).__name__}: {exc}", "stage": str(stage)}
        if stage.exists():
            _write_status(stage, "failed", **failed)
        (out / "export_last_attempt.json").write_text(json.dumps({"status": "failed", "at": datetime.now().isoformat(timespec="seconds"), **failed}, indent=1))
        raise


def _md_metrics(title: str, m: dict) -> list[str]:
    return [f"### {title}", "", "| n | pos | AUC | R@FPR2% | tau | precision | recall | FNR | FPR |", "|---|---|---|---|---|---|---|---|---|",
            f"| {m['n']} | {m['n_pos']} | {m['auc']:.4f} | {m['recall_at_fpr2']:.3f} | {m['tau']:.3f} | {m['precision']:.3f} | {m['recall']:.3f} | {m['fnr']:.3f} | {m['fpr']:.3f} |", ""]


def _require_bound_report(out: Path, json_name: str, md_name: str, info: dict, keys: tuple, render) -> dict:
    """A benchmark/DoA report enters the model card only if it was produced for this exact release and the
    markdown on disk is byte-for-byte what `render` produces from the bound JSON. Returns the parsed report."""
    jp, mp = out / json_name, out / "deliverables" / md_name
    if not jp.exists() or not mp.exists():
        raise ExportError(f"{md_name} missing: run its generator for this release before `export card`")
    report = json.loads(jp.read_text(encoding="utf-8"))
    meta = report.get("bound_to", {})
    bad = {k: (meta.get(k), info.get(k)) for k in keys if meta.get(k) != info.get(k)}
    if bad:
        raise ExportError(f"{md_name} was produced for a different release {bad}; re-run its generator")
    if mp.read_text(encoding="utf-8") != render(report):
        raise ExportError(f"{md_name} is not the markdown rendered from the current {json_name}; re-run its generator")
    return report


REQUIRED_PREDICTORS = ("float", "int8")  # the deployed int8 path must be benchmarked next to the float reference


def check_benchmark_coverage(report: dict, bench: dict) -> None:
    """Both predictors, their agreement entry, exactly n_nights distinct nights per predictor, every night at an
    approved SNR, and per-SNR aggregates that equal the recount of the per-night records."""
    want_snrs = {f"{float(s):g}" for s in bench["snrs_db"]}
    n_nights = int(bench["n_nights"])
    by_snr_all, nights_all = report.get("by_snr") or {}, report.get("nights") or {}
    if set(by_snr_all) != set(REQUIRED_PREDICTORS) or set(nights_all) != set(REQUIRED_PREDICTORS):
        raise ExportError(f"benchmark report must contain exactly the predictors {REQUIRED_PREDICTORS}; got {sorted(by_snr_all)} / {sorted(nights_all)}")
    if "float~int8" not in (report.get("agreement") or {}):
        raise ExportError("benchmark report lacks the float~int8 agreement entry")
    for name in REQUIRED_PREDICTORS:
        nights = nights_all[name]
        ids = [n.get("night") for n in nights]
        snr_of = {}
        for n in nights:
            snr_of[f"{float(n.get('snr_db')):g}"] = snr_of.get(f"{float(n.get('snr_db')):g}", 0) + 1
        if len(ids) != n_nights or len(set(ids)) != n_nights or not set(snr_of) <= want_snrs or set(snr_of) != want_snrs:
            raise ExportError(f"benchmark report for predictor {name} has {len(set(ids))} distinct nights over SNRs {sorted(snr_of)}; "
                              f"the approved benchmark is {n_nights} nights over SNRs {sorted(want_snrs)}; re-run python -m v5.benchmark_nights")
        agg = {f"{float(k):g}": int(m.get("nights", 0)) for k, m in by_snr_all[name].items()}
        if agg != snr_of or any(v <= 0 for v in agg.values()):
            raise ExportError(f"benchmark aggregates for predictor {name} {agg} do not match the per-night records {snr_of}; re-run python -m v5.benchmark_nights")
        # every aggregate value must be the generator's own aggregation of the per-night records
        from v5.benchmark_nights import _aggregate

        recomputed = {f"{float(k):g}": v for k, v in _aggregate(nights, sorted({n["snr_db"] for n in nights})).items()}
        reported = {f"{float(k):g}": v for k, v in by_snr_all[name].items()}
        for snr, want in recomputed.items():
            got = reported.get(snr, {})
            for field, value in want.items():
                if not _same_number(got.get(field), value):
                    raise ExportError(f"benchmark aggregate {field} at SNR {snr} for predictor {name} is {got.get(field)} but the per-night records give {value}; "
                                      "re-run python -m v5.benchmark_nights")


def check_doa_coverage(report: dict, sweep: dict) -> None:
    """Exactly one row per approved (spacing, distance, SNR) cell, each with the approved trial count and finite rates in [0, 1]."""
    want = {(f"{float(s):g}", f"{float(d):g}", f"{float(n):g}") for s in sweep["spacings_m"] for d in sweep["distances_m"] for n in sweep["snrs_db"]}
    seen = {}
    for r in report.get("rows") or []:
        key = (f"{float(r.get('spacing_m')):g}", f"{float(r.get('distance_m')):g}", f"{float(r.get('snr_db')):g}")
        seen[key] = seen.get(key, 0) + 1
        if int(r.get("trials", -1)) != int(sweep["trials"]):
            raise ExportError(f"DoA row {key} ran {r.get('trials')} trials; the approved sweep uses {sweep['trials']}; re-run python -m v5.doa_sim")
        for field in ("accuracy", "unknown_rate"):
            v = r.get(field)
            if not isinstance(v, (int, float)) or not math.isfinite(float(v)) or not 0.0 <= float(v) <= 1.0:
                raise ExportError(f"DoA row {key} has an invalid {field} {v!r}; re-run python -m v5.doa_sim")
    if set(seen) != want or any(c != 1 for c in seen.values()):
        raise ExportError(f"DoA report covers {len(seen)} cells ({sum(seen.values())} rows) but the approved sweep has {len(want)} cells, one row each; re-run python -m v5.doa_sim")


def _same_number(a, b, rel: float = 1e-9, abs_: float = 1e-12) -> bool:
    try:
        a, b = float(a), float(b)
    except (TypeError, ValueError):
        return False
    if math.isnan(a) or math.isnan(b):
        return math.isnan(a) and math.isnan(b)
    return math.isclose(a, b, rel_tol=rel, abs_tol=abs_)


def _consumption_history(out: Path) -> list[str]:
    """Every reset or migration of the test-consumption record, verbatim from the persistent ledger (spec 11)."""
    log = out / RESET_LEDGER
    if not log.exists():
        return []
    entries = [ln.strip() for ln in log.read_text(encoding="utf-8").splitlines() if ln.strip()]
    return ["test-consumption record history:", *[f"- {e}" for e in entries], ""]


def model_card(cfg: dict) -> str:
    out = Path(cfg["paths"]["out_dir"])
    deliv = out / "deliverables"
    status = json.loads((deliv / "export_status.json").read_text())
    if status["status"] != "ok":
        raise ExportError(f"last export did not pass the gates: {status}")
    info = json.loads((deliv / "export_info.json").read_text())
    from v5 import benchmark_nights as BN
    from v5 import doa_sim as DS

    bench_report = _require_bound_report(out, "benchmark_nights.json", "benchmark_nights.md", info,
                                         ("model_sha256", "tflite_sha256", "manifest_sha256", "tau", "fsm", "benchmark"), BN.to_markdown)
    check_benchmark_coverage(bench_report, info["benchmark"])
    doa_report = _require_bound_report(out, "doa_sim.json", "doa_sim.md", {**info, **info.get("doa_sweep", {})},
                                       ("model_sha256", "tflite_sha256", "manifest_sha256", "trials", "seed", "spacings_m", "distances_m", "snrs_db", "n_snore_windows"),
                                       lambda r: DS.to_markdown(r["rows"]))
    check_doa_coverage(doa_report, info["doa_sweep"])
    rob = json.loads((deliv / "robustness.json").read_text())
    cal = info.get("calib") or {}
    consumption = Path(cfg["paths"]["out_dir"]) / "test_consumption.json"
    consumed = json.loads(consumption.read_text()) if consumption.exists() else {}
    lines = [f"# SnoozMate v5 snore model card ({date.today().isoformat()})", "",
             f"test split consumed once by model {consumed.get('model_sha256', '?')[:12]} on manifest {consumed.get('manifest_sha256', '?')[:12]} at {consumed.get('at', '?')} "
             f"(tau {consumed.get('tau', float('nan')):.4f}; {len(consumed.get('bundle', {}))} bundle files hash-bound)", "",
             *_consumption_history(Path(cfg["paths"]["out_dir"])),
             f"model_version: `{info['model_version']}`; run `{info.get('run')}`; feature spec v{F.FEATURE_SPEC_VERSION}; tau = {info['tau']:.4f}; exported {info['exported_at']}", "",
             f"int8 TFLite: {info['tflite_bytes']} bytes (sha256 {info['tflite_sha256'][:12]}); params {info['params']}; input scale {info['qp']['input_scale']:.6f} zero point {info['qp']['input_zero_point']}; ops {info['qp'].get('ops')}", "",
             f"arena estimate: {info['arena']['activation_bytes_estimate']} bytes activations (largest tensor {info['arena']['largest_tensor_bytes']}); {info['arena']['note']}", "",
             f"calibration (calib split): n_neg {cal.get('n_neg')}, FPR {cal.get('fpr', float('nan')):.4f} (95% upper bound {cal.get('fpr_upper95', float('nan')):.4f}), recall {cal.get('recall', float('nan')):.3f}", "",
             "## Deployment call sequence", "", "```", "window (int16[16000], hop 8000) -> sf_compute -> sf_quantize(INPUT_SCALE, INPUT_ZERO_POINT)",
             "  -> TFLM invoke -> p = (out - OUTPUT_ZERO_POINT) * OUTPUT_SCALE -> fsm_tick(p, level_dbfs)", "  -> vibrate only while fsm.state == FSM_CONFIRMED and fsm.active", "```", "",
             "The handwritten float path (snore_infer.c, 63-frame input) is deprecated. Desktop C tests establish numerical parity, not ESP32-S3 deployability;",
             "the firmware build must still verify the TFLM operator resolver, the real tensor arena size and flash use.", ""]
    lines += _md_metrics("Test split, float model (evaluated once at export)", info["test"]["float"])
    lines += _md_metrics("Test split, int8 model (deployed path)", info["test"]["int8"])
    par = info["parity"]
    lines += ["### int8 parity gate", "", f"delta AUC {par['delta_auc']:.4f}; decision agreement {par['agreement']:.4f}; max |dp| {par['max_abs_diff']:.4f}; limits {info['parity_limits']}; passed: {par['passed']}", ""]
    lines += ["### Robustness (test split, float model)", "", "| condition | AUC | R@FPR2% | recall@tau | FPR@tau |", "|---|---|---|---|---|",
              f"| clean | {rob['clean']['auc']:.4f} | {rob['clean']['recall_at_fpr2']:.3f} | {rob['clean']['recall']:.3f} | {rob['clean']['fpr']:.3f} |"]
    for k, m in rob["snr"].items():
        lines.append(f"| SNR {k} dB | {m['auc']:.4f} | {m['recall_at_fpr2']:.3f} | {m['recall']:.3f} | {m['fpr']:.3f} |")
    for k, m in rob["distance"].items():
        lines.append(f"| RIR {k} m | {m['auc']:.4f} | {m['recall_at_fpr2']:.3f} | {m['recall']:.3f} | {m['fpr']:.3f} |")
    lines.append("")
    for name in ("cross_collection.md", "manifest_report.md", "experiments.md", "benchmark_nights.md", "doa_sim.md"):
        p = deliv / name
        if p.exists():
            lines += [f"## {name}", "", p.read_text(encoding="utf-8"), ""]
    return "\n".join(lines)


def release_binding(out_dir) -> dict:
    """Identifiers of the current release, used by the benchmark and DoA generators to bind their reports."""
    info = json.loads((Path(out_dir) / "deliverables" / "export_info.json").read_text(encoding="utf-8"))
    return {k: info[k] for k in ("model_sha256", "tflite_sha256", "manifest_sha256")}


def main(argv=None) -> None:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    h = sub.add_parser("headers")
    m = sub.add_parser("model")
    m.add_argument("--model", default=None)
    m.add_argument("--threshold", default=None)
    c = sub.add_parser("card")
    r = sub.add_parser("reset-test-record", help="document a reason in the ledger, then remove the test-consumption record and bundles")
    r.add_argument("--reason", required=True)
    for p in (h, m, c, r):
        p.add_argument("--config", default=None)
    args = ap.parse_args(argv)
    cfg = resolve(load_config(args.config))
    out = Path(cfg["paths"]["out_dir"])
    if args.cmd == "headers":
        thr = out / "deployed" / "threshold.json"
        tau = json.loads(thr.read_text())["tau"] if thr.exists() else 0.65
        write_headers_only(GEN_DIR, out / "deliverables" / "golden", FsmParams.from_config(tau, cfg["fsm"]), DoaParams(spacing_m=float(cfg["doa"]["spacing_m"])))
        print(f"headers -> {GEN_DIR}; golden -> {out / 'deliverables' / 'golden'}")
    elif args.cmd == "model":
        info = export_model(cfg, args.model, args.threshold)
        print(json.dumps({k: info[k] for k in ("model_version", "tau", "tflite_bytes", "params", "parity", "test")}, indent=1))
    elif args.cmd == "reset-test-record":
        ledger = reset_test_record(out, args.reason)
        print(f"reason recorded in {ledger}; record and bundles removed. The next `export model` evaluates the test split once more.")
    else:
        text = model_card(cfg)
        (out / "deliverables" / "model_card.md").write_text(text, encoding="utf-8")
        if (out / RESET_LEDGER).exists():
            shutil.copy(out / RESET_LEDGER, out / "deliverables" / RESET_LEDGER)  # ships with the card
        print(text[:2000])


if __name__ == "__main__":
    main()
