// Auto-generated by v5/export.py from the frozen feature spec; do not edit by hand.
#pragma once
#include <stddef.h>

extern const unsigned char snore_v5_int8_tflite[];
extern const unsigned int snore_v5_int8_tflite_len;
