// Auto-generated by v5/export.py from the frozen feature spec; do not edit by hand.
#pragma once

#define MODEL_VERSION "cnn_v5_int8"
#define FEATURE_SPEC_VERSION 1
#define INPUT_SCALE 0.0078431377f
#define INPUT_ZERO_POINT -1
#define OUTPUT_SCALE 0.0039062500f
#define OUTPUT_ZERO_POINT -128
#define SNORE_THRESHOLD 0.806049883f
#define FSM_TICK_MS 500
#define FSM_HOLD_TICKS 12
#define FSM_CONFIRM_TICKS 20
#define FSM_VERIFY_TICKS 30
#define FSM_MIN_BURSTS 3
#define FSM_PERIOD_MIN_TICKS 3
#define FSM_PERIOD_MAX_TICKS 14
